config/routes.rb
Loomio::Application.routes.draw do

  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end

  constraints(GroupSubdomainConstraints) do
    get '/' => 'redirect#group_subdomain'
    get '/d/:id(/:slug)', to: 'redirect#discussion_key'
    get '/g/:id(/:slug)', to: 'redirect#group_key'
    get '/m/:id(/:slug)', to: 'redirect#motion_key'
  end

  root to: 'root#index'

  resources(:development, only: :index) do
    get 'last_email', on: :collection, as: :last_email
    get ':action', on: :collection
  end

  namespace :admin do
    get 'url_info' => 'base#url_info'
    namespace :stats do
      get :bad_analytics
      get :group_activity
      get :daily_activity
      get :first_30_days
      get :retention
      get :events
      get :weekly_activity
      get :cohorts
      get :aaarrr
    end
  end

  ActiveAdmin.routes(self)

  namespace :popolo, path: '/api/popolo', defaults: {format: :json} do
    resources :motions, only: :index
  end

  namespace :api, path: '/api/v1', defaults: {format: :json} do

    resources :groups, only: [:index, :show, :create, :update] do
      get :subgroups, on: :member
      get :count_explore_results, on: :collection
      patch :archive, on: :member
      put :archive, on: :member
      post :use_gift_subscription, on: :member
      post 'upload_photo/:kind', on: :member, action: :upload_photo
    end

    resources :users, only: :show

    resources :memberships, only: [:index, :create, :update, :destroy] do
      collection do
        post :add_to_subgroup
        post :join_group
        get :autocomplete
        get :for_user
        get :my_memberships
        get :invitables
      end
      member do
        post :make_admin
        post :remove_admin
        post :save_experience
        patch :set_volume
      end
    end

    resources :membership_requests, only: [:create] do
      collection do
        get :my_pending
        get :pending
        get :previous
      end
      post :approve, on: :member
      post :ignore, on: :member
    end

    resources :invitations, only: [:create, :destroy] do
      get :pending, on: :collection
      get :shareable, on: :collection
    end

    resources :profile, only: [:show] do
      post :update_profile, on: :collection
      post :set_volume, on: :collection
      post :upload_avatar, on: :collection
      post :change_password, on: :collection
      post :deactivate, on: :collection
      post :save_experience, on: :collection
    end

    resources :events, only: :index
    resources :drafts do
      collection do
        get    '/:draftable_type/:draftable_id', action: :show
        post   '/:draftable_type/:draftable_id', action: :update
        patch  '/:draftable_type/:draftable_id', action: :update
        put    '/:draftable_type/:draftable_id', action: :update
      end
    end

    resources :discussions, only: [:show, :index, :create, :update, :destroy] do
      patch :mark_as_read, on: :member
      patch :set_volume, on: :member
      patch :star, on: :member
      patch :unstar, on: :member
      patch :move, on: :member
      put :mark_as_read, on: :member
      put :set_volume, on: :member
      put :star, on: :member
      put :unstar, on: :member
      put :move, on: :member
      get :dashboard, on: :collection
      get :inbox, on: :collection
    end

    resources :search, only: :index

    resources :motions,     only: [:show, :index, :create, :update], path: :proposals do
      post :close, on: :member
      post :create_outcome, on: :member
      post :update_outcome, on: :member
      get  :closed, on: :collection
    end

    resources :votes,       only: [       :index, :create, :update] do
      get :my_votes, on: :collection
    end

    resources :did_not_votes, only: :index

    resources :comments,    only: [:create, :update, :destroy] do
      post :like, on: :member
      post :unlike, on: :member
    end

    resources :attachments, only: [:create, :destroy]

    resources :motions, only: :create do
      post :vote, on: :member
    end

    resource :translations, only: :show do
      get :inline, to: 'translations#inline'
    end

    resources :notifications, only: :index do
      post :viewed, on: :collection
    end

    resources :contact_messages, only: :create

    resources :versions, only: :index

    resources :oauth_applications, only: [:show, :create, :update, :destroy] do
      post :revoke_access, on: :member
      post :upload_logo, on: :member
      get :owned, on: :collection
      get :authorized, on: :collection
    end

    namespace(:message_channel) { post :subscribe }
    namespace(:sessions)        { get :unauthorized }
    devise_scope :user do
      resource :sessions, only: [:create, :destroy]
      resource :registrations, only: :create
    end
  end

  get '/discussions/:id', to: 'redirect#discussion_id'
  get '/groups/:id',      to: 'redirect#group_id'
  get '/motions/:id',     to: 'redirect#motion_id'

  get "/browser_not_supported", to: "application#browser_not_supported"

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace(:subscriptions) { post :webhook }
  resources :invitations, only: [:show]
  get '/users/invitation/accept' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('invitation_token=','')}"}

  namespace :email_actions do
    get   'unfollow_discussion/:discussion_id/:unsubscribe_token', action: 'unfollow_discussion', as: :unfollow_discussion
    get   'follow_discussion/:discussion_id/:unsubscribe_token',   action: 'follow_discussion',   as: :follow_discussion
    get   'mark_summary_email_as_read', action: 'mark_summary_email_as_read', as: :mark_summary_email_as_read
    get   'mark_discussion_as_read/:discussion_id/:event_id/:unsubscribe_token', action: 'mark_discussion_as_read', as: :mark_discussion_as_read
  end

  scope controller: 'help' do
    get :markdown
  end

  get 'contact(/:destination)', to: 'contact_messages#new'
  post :contact, to: 'contact_messages#create', as: :contact
  post :email_processor, to: 'griddler/emails#create'

  get '/robots'     => 'robots#show'
  get '/manifest'   => 'manifest#show', format: :json

  get  'start_group' => 'start_group#new'
  post 'start_group' => 'start_group#create'

  get 'g/:key/export'                      => 'groups#export',    as: :group_export
  get 'g/:key(/:slug)'                     => 'groups#show',      as: :group
  get 'd/:key(/:slug)'                     => 'discussions#show', as: :discussion
  get 'd/:key/comment/(:id)'               => 'discussions#show', as: :comment
  get 'm/:key(/:slug)'                     => 'motions#show',     as: :motion
  get 'u/:username/'                       => 'users#show',       as: :user

  get 'dashboard'                          => 'application#boot_angular_ui', as: :dashboard
  get 'dashboard/:filter'                  => 'application#boot_angular_ui'
  get 'inbox'                              => 'application#boot_angular_ui', as: :inbox
  get 'groups'                             => 'application#boot_angular_ui', as: :groups
  get 'explore'                            => 'application#boot_angular_ui', as: :explore
  get 'profile'                            => 'application#boot_angular_ui', as: :profile
  get 'email_preferences'                  => 'application#boot_angular_ui', as: :email_preferences
  get 'apps/registered'                    => 'application#boot_angular_ui'
  get 'apps/authorized'                    => 'application#boot_angular_ui'
  get 'apps/registered/:id'                => 'application#boot_angular_ui'
  get 'apps/registered/:id/:slug'          => 'application#boot_angular_ui'
  get 'd/:key/proposal/:proposal'          => 'application#boot_angular_ui', as: :discussion_motion
  get 'd/:key/comment/:comment'            => 'application#boot_angular_ui', as: :discussion_comment
  get 'd/:key/proposal/:proposal/:outcome' => 'application#boot_angular_ui', as: :discussion_motion_outcome
  get 'g/:key/membership_requests'         => 'application#boot_angular_ui', as: :group_membership_requests
  get 'g/:key/memberships'                 => 'application#boot_angular_ui', as: :group_memberships
  get 'g/:key/previous_proposals'          => 'application#boot_angular_ui', as: :group_previous_proposals
  get 'g/:key/memberships/:username'       => 'application#boot_angular_ui'

  get '/notifications/dropdown_items'      => 'application#gone'
  get '/u/:key(/:stub)'                    => 'application#gone'
  get '/g/:key/membership_requests/new'    => 'application#gone'
  get '/comments/:id'                      => 'application#gone'
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base

  class InvitationCancelled < StandardError
  end

  class InvitationAlreadyUsed < StandardError
  end

  extend FriendlyId
  friendly_id :token
  belongs_to :inviter, class_name: User
  belongs_to :invitable, polymorphic: true
  belongs_to :canceller, class_name: User

  update_counter_cache :invitable, :invitations_count

  validates_presence_of :invitable, :intent
  validates_inclusion_of :invitable_type, :in => ['Group', 'Discussion']
  validates_inclusion_of :intent, :in => ['start_group', 'join_group', 'join_discussion']
  scope :chronologically, -> { order('id asc') }
  before_save :ensure_token_is_present

  delegate :name, to: :inviter, prefix: true, allow_nil: true

  scope :not_cancelled,  -> { where(cancelled_at: nil) }
  scope :pending, -> { not_cancelled.single_use.where(accepted_at: nil) }
  scope :shareable, -> { not_cancelled.where(single_use: false) }
  scope :single_use, -> { not_cancelled.where(single_use: true) }
  scope :ignored, -> (send_count, since) { pending.where(send_count: send_count).where('created_at < ?', since) }

  alias :group :invitable

  def invitable_name
    invitable&.full_name
  end

  def cancel!(args = {})
    update!(args.slice(:canceller).merge(cancelled_at: DateTime.now))
  end

  def cancelled?
    invitable.blank? || cancelled_at
  end

  def accepted?
    accepted_at.present?
  end

  def to_start_group?
    intent == 'start_group'
  end

  def to_join_group?
    intent == 'join_group'
  end

  def is_pending?
    !cancelled? && !accepted?
  end

  private
  def ensure_token_is_present
    set_unique_token unless self.token
  end

  def set_unique_token
    begin
      token = SecureRandom.hex.slice(0, 20)
    end while self.class.where(token: token).exists?
    self.token = token
  end

end

app/controllers/api/invitations_controller.rb
class API::InvitationsController < API::RestfulController
  def create
    load_and_authorize :group, :invite_people
    @invitations = InvitationService.invite_to_group(recipient_emails: email_addresses,
                                                     group: @group,
                                                     inviter: current_user,
                                                     message: invitation_form_params[:message])
    if @invitations.any?
      respond_with_collection
    else
      respond_with_errors
    end
  end

  def pending
    load_and_authorize :group, :view_pending_invitations
    @invitations = page_collection(@group.invitations.pending)
    respond_with_collection
  end

  def shareable
    load_and_authorize :group, :view_shareable_invitation
    @invitations = [InvitationService.shareable_invitation_for(@group)]
    respond_with_collection
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    InvitationService.cancel(invitation: @invitation, actor: current_user)
    respond_with_resource
  end

  private

  def invitation_form_params
    params.require(:invitation_form)
  end

  def email_addresses
    invitation_form_params[:emails].scan(/[^\s,;<>]+?@[^\s,;<>]+\.[^\s,;<>]+/).take(100)
  end

  def respond_with_errors
    render json: {errors: { emails: [  I18n.t('invitation_form.error.all_email_addresses_belong_to_members') ]}}, root: false, status: 422
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  include PrettyUrlHelper

  rescue_from(ActiveRecord::RecordNotFound)    { respond_with_error :"invitation.invitation_not_found", status: :not_found }
  rescue_from(Invitation::InvitationCancelled) { respond_with_error :"invitation.invitation_cancelled" }
  rescue_from(Invitation::InvitationAlreadyUsed) do
    if current_user_or_visitor.email == invitation.recipient_email
      redirect_to invitation.invitable
    else
      respond_with_error :"invitation.invitation_already_used"
    end
  end

  def show
    if current_user_or_visitor.is_logged_in?
      InvitationService.redeem(invitation, current_user)
      session[:invitation_token] = nil
      redirect_to group_url(invitation.invitable)
    else
      session[:invitation_token] = params[:id]
      redirect_to login_or_signup_path_for_email(invitation.recipient_email)
    end
  end

  private

  def invitation
    @invitation ||= Invitation.find_by_token!(params[:id])
  end
end

app/views/invitations/_form.html.haml
.row
  .col-md-4.offset3
    .signup-form
      %p
        %strong= t :"devise.registrations.sign_up"
        %br
    =simple_form_for(@user, url: user_registration_path) do |f|
      =f.input :name, :input_html => { :value => @user_name }
      =f.input :email, :input_html => { :value => @invitation.recipient_email }
      =f.input :password
      =f.input :password_confirmation
      =f.input :language_preference, :collection => {"English" => "en", "Español" => "es", "ελληνικά" => "el"}, selected: I18n.locale, include_blank: false
      =f.submit t("devise.registrations.sign_up"), class: "btn btn-info btn-lg"
.row
  .col-md-6.offset3
    %p= t :"or_sign_in_html", link: user_session_path

app/views/invitations/_invite_users.html.haml
- if @group.is_subgroup?
  %h3= t("invitation.by_email")
.form-group
  %p= t("invitation.recipients")
  = text_area_tag 'invitees', nil, class: 'validate-emails form-control js-autocomplete-contacts', placeholder: t("invitation.invitees_placeholder"), data: {autocomplete_path: autocomplete_contacts_path}
  -#.email-validation-help= t('error.invalid_email')
  %p
    %small= t(:'invitation.import_contacts_html', google_link: link_to(t(:google), import_contacts_path(from: 'gmail')))
  = form.input :recipients, as: :hidden, input_html: { class: 'recipients' }

.form-group
  - if @discussion.present?
    = form.input :message_body, label: t("invitation.message_body"), as: :text, input_html: { value: t("invitation.body_editable_discussion", group: group.name) }
  - else
    = form.input :message_body, label: t("invitation.message_body"), as: :text, input_html: { value: t("invitation.body_editable", group: group.name) }

  %p= t(:'invitation.angular_warning_html')

app/views/invitations/_title.html.haml
.group-title
  - if group
    %h1.home-title
      = link_to t(:home), "/"
      = content_tag :span, "\u25B6", class: 'name-separator'
      - if group.is_subgroup?
        = link_to group.parent.name, group.parent
        = content_tag :span, "\u25B6", class: 'name-separator'
      = link_to group.name, group
      - if discussion.present?
        = content_tag :span, "\u25B6", class: 'name-separator'
        = link_to discussion.title
    = render 'groups/privacy_dropdown', :group => group
  - else
    %h1.home-title
      = link_to t(:home), "/"

app/views/invitations/new.html.haml
= render 'title', group: @group, discussion: @discussion
= simple_form_for(@invite_people_form, url: invitations_path, method: :post) do |f|
  - if @invitable.kind_of?(Group)
    = hidden_field_tag :group_id, @invitable.key
  - elsif @invitable.kind_of?(Discussion)
    = hidden_field_tag :discussion_id, @invitable.key

  .row#invitations-header
    %h1= t("invitation.invite_people")
  .row#invitation-options
    .col-sm-6.invite-by-email
      = render 'invite_users', form: f, group: @group, discussion: @discussion
    - if @group.is_subgroup?
      .col-sm-5.col-sm-offset-1.invite-members-of-parent
        %h3= t :"invitation.select_members", group_name: @group.parent.name
        .parent-members
          - addable_users = @group.parent_members.sorted_by_name.map{|u| [u.name, u.id] }
          - existing_user_ids = @group.members.map(&:id)
          - if addable_users.count > 1
            .invite-member-checkbox-container
              = f.input :parent_members_to_add, collection: addable_users, as: :check_boxes, label: false, disabled: existing_user_ids, checked: existing_user_ids

          - else
            =t :empty_parent_group
  .row
    .col-sm-5.invitation-submit
      = f.submit t("invite_people"), :class => "btn btn-primary btn-lg run-validations", :id => "invite-to-group", :data => { disable_with: t("invite_people") }